---
title: "Untitled"
author: "Yunting Chiu"
date: "10/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
mpg %>%
  select_if(is.character) 
```

```{r}
mtcars
```
- Transform the data so AC, Pool and Highway are factors and Price is in thousands of dollars.
```{r}
# Transform the data so AC, Pool and Highway are factors and Price is in thousands of dollars.
estate <- read_csv("../housing_app/data/estate.csv",
                   col_types = cols("AC" = col_factor(),
                                    "Pool" = col_factor(),
                                    "Highway" = col_factor())) %>%
          mutate(Price = round(Price/1000)) %>%
          rename("Price($K)" = "Price") %>%
          mutate(AC = fct_recode(AC, "Presence" = "1", "Absence" = "0"),
                 Pool = fct_recode(Pool, "Pool" = "1", "No Pool" = "0"),
                 Highway = fct_recode(Highway, "Adjacent" = "1", "Not Adjacent" = "0")) -> estate
estate
```

```{r}
ls(estate)
```

```{r}
estate %>%
```
```{r}
mtcars %>% select_if(is_whole, toupper)
```

